-- SQL_GETALL_SYUTSURYOKU_SELECT
SELECT a.管理No,b.受注番号,b.枝番,b.品番,b.設変番号,b.受注日,b.納期,0 AS 工程順序No,'' AS 作業区コード,'' AS 作業区名,NULL AS 発注日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,b.得意先コード,COALESCE(d.得意先略称,'') AS 得意先名 FROM T_生産計画 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.受注区分 <> '2' LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード WHERE NOT EXISTS (SELECT * FROM T_発注 WHERE 管理No = a.管理No) AND a.生産数 <> 0
-- SQL_GETALL_SYUTSURYOKU_TANTOUSYA
AND b.担当者コード = ?
-- SQL_GETALL_SYUTSURYOKU_ZYUCHUUBANGOU
AND b.受注番号 &@ ? AND LENGTH(b.受注番号) = LENGTH(?)
-- SQL_GETALL_SYUTSURYOKU_HINBAN
AND b.品番 &@ ? AND LENGTH(b.品番) = LENGTH(?)
-- SQL_GETALL_SYUTSURYOKU_ORDER_BY
ORDER BY b.受注番号, b.枝番
-- SQL_GETALL_TORIKESHI_SELECT
SELECT a.管理No,b.受注番号,b.枝番,b.品番,b.設変番号,b.受注日,b.納期,0 AS 工程順序No,'' AS 作業区コード,'' AS 作業区名,e.発注日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,b.得意先コード,COALESCE(d.得意先略称,'') AS 得意先名 FROM T_生産計画 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.受注区分 <> '2' LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード INNER JOIN (SELECT DISTINCT 管理No, 発注日 FROM T_発注 WHERE 発注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)) AS e ON e.管理No = a.管理No WHERE NOT EXISTS (SELECT * FROM T_工程受入 WHERE 管理No = a.管理No)
-- SQL_GETALL_TORIKESHI_TANTOUSYA
AND b.担当者コード = ?
-- SQL_GETALL_TORIKESHI_ZYUCHUUBANGOU
AND b.受注番号 &@ ? AND LENGTH(b.受注番号) = LENGTH(?)
-- SQL_GETALL_TORIKESHI_HINBAN
AND b.品番 &@ ? AND LENGTH(b.品番) = LENGTH(?)
-- SQL_GETALL_TORIKESHI_ORDER_BY
ORDER BY b.受注番号, b.枝番
-- SQL_GETALL_SAISYUTSURYOKU_SELECT
SELECT a.管理No,b.受注番号,b.枝番,b.品番,b.設変番号,b.受注日,b.納期,f.工程順序No,f.作業区コード,COALESCE(g.作業区略称,'') AS 作業区名,e.発注日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,b.得意先コード,COALESCE(d.得意先略称,'') AS 得意先名 FROM T_生産計画 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.受注区分 <> '2' LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード INNER JOIN (SELECT DISTINCT 管理No, 発注日 FROM T_発注 WHERE 発注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)) AS e ON e.管理No = a.管理No INNER JOIN T_生産計画詳細 AS f ON f.管理No = a.管理No LEFT OUTER JOIN M_作業区仕入先 AS g ON g.作業区コード = f.作業区コード WHERE 1=1
-- SQL_GETALL_SAISYUTSURYOKU_TANTOUSYA
AND b.担当者コード = ?
-- SQL_GETALL_SAISYUTSURYOKU_ZYUCHUUBANGOU
AND b.受注番号 &@ ? AND LENGTH(b.受注番号) = LENGTH(?)
-- SQL_GETALL_SAISYUTSURYOKU_HINBAN
AND b.品番 &@ ? AND LENGTH(b.品番) = LENGTH(?)
-- SQL_GETALL_SAISYUTSURYOKU_ORDER_BY
ORDER BY b.受注番号, b.枝番, f.工程順序No
-- SQL_GETALL_SYUTSURYOKU_BUNNOU_SELECT
SELECT a.管理No,b.受注番号,b.枝番,b.品番,b.設変番号,b.受注日,b.納期,f.工程順序No,f.作業区コード,COALESCE(g.作業区略称,'') AS 作業区名,e.発注日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,b.得意先コード,COALESCE(d.得意先略称,'') AS 得意先名 FROM T_生産計画 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.受注区分 <> '2' LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード INNER JOIN T_生産計画詳細 AS f ON f.管理No = a.管理No INNER JOIN T_発注 AS e ON e.管理No = f.管理No AND e.工程順序No = f.工程順序No LEFT OUTER JOIN M_作業区仕入先 AS g ON g.作業区コード = f.作業区コード WHERE NOT EXISTS (SELECT * FROM T_工程受入 WHERE 管理No = f.管理No AND 工程順序No = f.工程順序No AND 受入形態区分 IN ('1','2')) AND EXISTS (SELECT * FROM T_工程受入 WHERE 管理No = f.管理No AND 工程順序No = f.工程順序No AND 受入形態区分 = '3' AND 受入日 BETWEEN CAST(? as DATE) AND CAST(? as DATE) AND 受入日 > COALESCE(e.分納発注書出力日,'2000-01-01')) AND COALESCE(g.分納発注書発行区分,false) = true
-- SQL_GETALL_SYUTSURYOKU_BUNNOU_TANTOUSYA
AND b.担当者コード = ?
-- SQL_GETALL_SYUTSURYOKU_BUNNOU_ZYUCHUUBANGOU
AND b.受注番号 &@ ? AND LENGTH(b.受注番号) = LENGTH(?)
-- SQL_GETALL_SYUTSURYOKU_BUNNOU_HINBAN
AND b.品番 &@ ? AND LENGTH(b.品番) = LENGTH(?)
-- SQL_GETALL_SYUTSURYOKU_BUNNOU_ORDER_BY
ORDER BY b.受注番号, b.枝番, f.工程順序No
-- SQL_REPORT_SYUTSURYOKU
SELECT a.管理No,b.工程順序No,b.作業区コード,COALESCE(d.作業区名,'') AS 作業区名,CURRENT_DATE AS 発注日,b.納期,c.品番,c.設変番号,c.品名,c.受注番号,c.枝番,b.工程コード,COALESCE(e.工程名,'') AS 工程名,COALESCE(g.作業区名,'') AS 前工程作業区名,f.納期 AS 前工程納期,CASE WHEN h.作業区コード IS NULL THEN '古河（本社）' ELSE COALESCE(i.作業区名,'') END AS 次工程作業区名,0 AS 伝票番号,a.生産数 AS 発注数,c.単位,CASE WHEN b.加工費区分 = true OR b.材料費区分 = true THEN 0.00 ELSE b.加工費 + b.材料費 END AS 発注単価 ,CASE WHEN b.加工費区分 = true OR b.材料費区分 = true THEN 0 ELSE CAST(trunc((b.加工費 + b.材料費) * a.生産数,0) as BIGINT) END AS 発注金額 ,c.発注備考1,c.発注備考2,COALESCE(k.社員名,'') AS 担当者名,CASE WHEN l.品番 IS NULL THEN '0' ELSE '1' END AS 管理マーク,CASE WHEN c.受注区分 <> '4' THEN '0' ELSE '1' END AS 再納マーク,CASE c.再納区分 WHEN '1' THEN '不合格選別依頼' WHEN '2' THEN '不合格再処理' WHEN '3' THEN '不合格再製造' ELSE '' END AS 再納マーク種類 ,CASE WHEN h.作業区コード IS NULL THEN 1 ELSE 0 END AS 最終工程区分,b.材料費 FROM T_生産計画 AS a INNER JOIN T_生産計画詳細 AS b ON b.管理No = a.管理No INNER JOIN T_受注 AS c ON c.管理No = a.管理No LEFT OUTER JOIN M_作業区仕入先 AS d ON d.作業区コード = b.作業区コード LEFT OUTER JOIN M_工程 AS e ON e.工程コード = b.工程コード LEFT OUTER JOIN T_生産計画詳細 AS f ON f.管理No = b.管理No AND f.工程順序No = (b.工程順序No - 1) LEFT OUTER JOIN M_作業区仕入先 AS g ON g.作業区コード = f.作業区コード LEFT OUTER JOIN T_生産計画詳細 AS h ON h.管理No = b.管理No AND h.工程順序No = (b.工程順序No + 1) LEFT OUTER JOIN M_作業区仕入先 AS i ON i.作業区コード = h.作業区コード LEFT OUTER JOIN M_社員 AS k ON k.社員コード = c.担当者コード LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS l ON l.品番 = c.品番 WHERE a.管理No = CAST(? AS INT) ORDER BY b.管理No, b.工程順序No
-- SQL_REPORT_TORIKESHI
SELECT a.管理No,a.作業区コード,COALESCE(b.作業区名,'') AS 作業区名,a.発注日,a.納期,c.品番,c.設変番号,c.品名,c.受注番号,c.枝番,a.工程コード,COALESCE(d.工程名,'') AS 工程名,COALESCE(f.作業区名,'') AS 前工程作業区名,e.納期 AS 前工程納期,CASE WHEN g.作業区コード IS NULL THEN '古河（本社）' ELSE COALESCE(h.作業区名,'') END AS 次工程作業区名,a.伝票番号,a.発注数,c.単位,a.単価 AS 発注単価,CAST(trunc(a.単価 * a.発注数 ,0) as BIGINT) AS 発注金額,c.発注備考1,c.発注備考2,COALESCE(i.社員名,'') AS 担当者名,CASE WHEN j.品番 IS NULL THEN '0' ELSE '1' END AS 管理マーク,CASE WHEN c.受注区分 <> '4' THEN '0' ELSE '1' END AS 再納マーク,CASE c.再納区分 WHEN '1' THEN '不合格選別依頼' WHEN '2' THEN '不合格再処理' WHEN '3' THEN '不合格再製造' ELSE '' END AS 再納マーク種類 FROM T_発注 AS a LEFT OUTER JOIN M_作業区仕入先 AS b ON b.作業区コード = a.作業区コード INNER JOIN T_受注 AS c ON c.管理No = a.管理No LEFT OUTER JOIN M_工程 AS d ON d.工程コード = a.工程コード LEFT OUTER JOIN T_生産計画詳細 AS e ON e.管理No = a.管理No AND e.工程順序No = (a.工程順序No - 1) LEFT OUTER JOIN M_作業区仕入先 AS f ON f.作業区コード = e.作業区コード LEFT OUTER JOIN T_生産計画詳細 AS g ON g.管理No = a.管理No AND g.工程順序No = (a.工程順序No + 1) LEFT OUTER JOIN M_作業区仕入先 AS h ON h.作業区コード = g.作業区コード LEFT OUTER JOIN M_社員 AS i ON i.社員コード = c.担当者コード LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS j ON j.品番 = c.品番 WHERE a.管理No = CAST(? AS INT) ORDER BY a.管理No, a.工程順序No
-- SQL_REPORT_SAISYUTSURYOKU
SELECT a.管理No,c.作業区コード,COALESCE(d.作業区名,'') AS 作業区名,a.発注日,c.納期,e.品番,e.設変番号,e.品名,e.受注番号,e.枝番,c.工程コード,COALESCE(f.工程名,'') AS 工程名,COALESCE(h.作業区名,'') AS 前工程作業区名,g.納期 AS 前工程納期,CASE WHEN i.作業区コード IS NULL THEN '古河（本社）' ELSE COALESCE(j.作業区名,'') END AS 次工程作業区名,a.伝票番号,b.生産数 AS 発注数,e.単位,CASE WHEN c.加工費区分 = true OR c.材料費区分 = true THEN 0.00 ELSE c.加工費 + c.材料費 END AS 発注単価 ,CASE WHEN c.加工費区分 = true OR c.材料費区分 = true THEN 0 ELSE CAST(trunc((c.加工費 + c.材料費) * b.生産数 ,0) as BIGINT) END AS 発注金額 ,e.発注備考1,e.発注備考2,COALESCE(k.社員名,'') AS 担当者名,CASE WHEN l.品番 IS NULL THEN '0' ELSE '1' END AS 管理マーク,CASE WHEN e.受注区分 <> '4' THEN '0' ELSE '1' END AS 再納マーク,CASE e.再納区分 WHEN '1' THEN '不合格選別依頼' WHEN '2' THEN '不合格再処理' WHEN '3' THEN '不合格再製造' ELSE '' END AS 再納マーク種類 FROM T_発注 AS a INNER JOIN T_生産計画 AS b ON b.管理No = a.管理No INNER JOIN T_生産計画詳細 AS c ON c.管理No = a.管理No AND c.工程順序No = a.工程順序No LEFT OUTER JOIN M_作業区仕入先 AS d ON d.作業区コード = c.作業区コード INNER JOIN T_受注 AS e ON e.管理No = a.管理No LEFT OUTER JOIN M_工程 AS f ON f.工程コード = c.工程コード LEFT OUTER JOIN T_生産計画詳細 AS g ON g.管理No = a.管理No AND g.工程順序No = (a.工程順序No - 1) LEFT OUTER JOIN M_作業区仕入先 AS h ON h.作業区コード = g.作業区コード LEFT OUTER JOIN T_生産計画詳細 AS i ON i.管理No = a.管理No AND i.工程順序No = (a.工程順序No + 1) LEFT OUTER JOIN M_作業区仕入先 AS j ON j.作業区コード = i.作業区コード LEFT OUTER JOIN M_社員 AS k ON k.社員コード = e.担当者コード LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS l ON l.品番 = e.品番 WHERE a.管理No = CAST(? AS INT) AND a.工程順序No = CAST(? AS INT) ORDER BY a.管理No, a.工程順序No
-- SQL_REPORT_BUNNOU_HACCHUU
SELECT a.管理No,a.作業区コード,COALESCE(b.作業区名,'') AS 作業区名,a.発注日,a.納期,c.品番,c.設変番号,c.品名,c.受注番号,c.枝番,a.工程コード,COALESCE(d.工程名,'') AS 工程名,COALESCE(f.作業区名,'') AS 前工程作業区名,e.納期 AS 前工程納期,CASE WHEN g.作業区コード IS NULL THEN '古河（本社）' ELSE COALESCE(h.作業区名,'') END AS 次工程作業区名,a.伝票番号,(a.発注数 - k.受入数) AS 発注数,c.単位,a.単価 AS 発注単価,CAST(trunc(a.単価 * (a.発注数 - k.受入数),0) as BIGINT) AS 発注金額,c.発注備考1,c.発注備考2,COALESCE(i.社員名,'') AS 担当者名,CASE WHEN l.品番 IS NULL THEN '0' ELSE '1' END AS 管理マーク,CASE WHEN c.受注区分 <> '4' THEN '0' ELSE '1' END AS 再納マーク,CASE c.再納区分 WHEN '1' THEN '不合格選別依頼' WHEN '2' THEN '不合格再処理' WHEN '3' THEN '不合格再製造' ELSE '' END AS 再納マーク種類 FROM T_発注 AS a LEFT OUTER JOIN M_作業区仕入先 AS b ON b.作業区コード = a.作業区コード INNER JOIN T_受注 AS c ON c.管理No = a.管理No LEFT OUTER JOIN M_工程 AS d ON d.工程コード = a.工程コード LEFT OUTER JOIN T_生産計画詳細 AS e ON e.管理No = a.管理No AND e.工程順序No = (a.工程順序No - 1) LEFT OUTER JOIN M_作業区仕入先 AS f ON f.作業区コード = e.作業区コード LEFT OUTER JOIN T_生産計画詳細 AS g ON g.管理No = a.管理No AND g.工程順序No = (a.工程順序No + 1) LEFT OUTER JOIN M_作業区仕入先 AS h ON h.作業区コード = g.作業区コード LEFT OUTER JOIN M_社員 AS i ON i.社員コード = c.担当者コード INNER JOIN (SELECT 管理No, 工程順序No, SUM(受入数) AS 受入数 FROM T_工程受入 GROUP BY 管理No, 工程順序No) AS k ON k.管理No = a.管理No AND k.工程順序No = a.工程順序No LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS l ON l.品番 = c.品番 WHERE a.管理No = CAST(? AS INT) AND a.工程順序No = CAST(? AS INT) ORDER BY a.管理No, a.工程順序No
-- SQL_REPORT_HENPIN
SELECT a.管理No, a.作業区コード, COALESCE(b.作業区名,'') AS 作業区名, a.発注日, a.納期, c.品番, c.設変番号, c.品名, c.受注番号, c.枝番, a.工程コード, COALESCE(d.工程名,'') AS 工程名, COALESCE(f.作業区名,'') AS 前工程作業区名, e.納期 AS 前工程納期, CASE WHEN g.作業区コード IS NULL THEN '古河（本社）' ELSE COALESCE(h.作業区名,'') END AS 次工程作業区名, a.伝票番号, k.数量 AS 返品数, c.単位, k.単価 AS 返品単価,CAST(trunc(k.単価 * k.数量 ,0) as BIGINT) AS 返品金額, k.備考 AS 返品備考1, '返品日：' || TO_CHAR(k.返品日, 'YYYY/MM/DD') AS 返品備考2, COALESCE(i.社員名,'') AS 担当者名, CASE WHEN l.品番 IS NULL THEN '0' ELSE '1' END AS 管理マーク, CASE WHEN c.受注区分 <> '4' THEN '0' ELSE '1' END AS 再納マーク, CASE c.再納区分 WHEN '1' THEN '不合格選別依頼' WHEN '2' THEN '不合格再処理' WHEN '3' THEN '不合格再製造' ELSE '' END AS 再納マーク種類 FROM T_受入返品 AS k INNER JOIN T_発注 AS a ON k.管理No = a.管理No AND k.工程順序No = a.工程順序No LEFT OUTER JOIN M_作業区仕入先 AS b ON b.作業区コード = a.作業区コード INNER JOIN T_受注 AS c ON c.管理No = a.管理No LEFT OUTER JOIN M_工程 AS d ON d.工程コード = a.工程コード LEFT OUTER JOIN T_生産計画詳細 AS e ON e.管理No = a.管理No AND e.工程順序No = (a.工程順序No - 1) LEFT OUTER JOIN M_作業区仕入先 AS f ON f.作業区コード = e.作業区コード LEFT OUTER JOIN T_生産計画詳細 AS g ON g.管理No = a.管理No AND g.工程順序No = (a.工程順序No + 1) LEFT OUTER JOIN M_作業区仕入先 AS h ON h.作業区コード = g.作業区コード LEFT OUTER JOIN M_社員 AS i ON i.社員コード = c.担当者コード LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS l ON l.品番 = c.品番 WHERE k.SeqNo = CAST(? AS INT) ORDER BY a.管理No, a.工程順序No
-- SQL_REPORT_SHIRE_HENPIN
SELECT a.仕入先コード ,COALESCE(b.作業区名,'') AS 作業区名 ,CASE WHEN a.取引分類 = '1' THEN a.材質名 ELSE a.品番 END AS 品番 ,CASE WHEN a.取引分類 = '1' THEN '' ELSE a.設変番号 END AS 設変番号 ,CASE WHEN a.取引分類 = '1' THEN a.形状 ELSE a.品名 END AS 品名 ,CASE WHEN a.取引分類 = '1' THEN a.重量 ELSE a.数量 END AS 数量 ,CASE WHEN a.取引分類 = '1' THEN CASE WHEN a.材料単位 = '1' THEN '㎏' ELSE '本' END ELSE '' END AS 単位 ,a.単価 ,- a.金額 AS 金額 ,a.備考 AS 備考1 ,'返品日：' || TO_CHAR(a.取引日, 'YYYY/MM/DD') AS 備考2 FROM T_仕入 AS a LEFT OUTER JOIN M_作業区仕入先 AS b ON b.作業区コード = a.仕入先コード WHERE SeqNo = CAST(? AS INT)
-- SQL_MULTIPLE
SELECT CAST(値 as INT) FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ? AND Key3 = ?

