-- SQL_GET_ALL_COUNT
SELECT CAST(COUNT(A.管理No) AS INT)
-- SQL_GET_ALL_NEW_KENSA_SELECT
SELECT A.管理No ,COALESCE(C.分納No,0) + 1 AS 分納No ,A.受注番号 ,A.枝番 ,A.品番 ,A.設変番号 ,A.納期 ,A.受注数 ,C.依頼日 ,C.依頼数 ,A.担当者コード ,COALESCE(D.社員名,'') AS 担当者名 ,CASE A.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分 ,A.得意先コード ,COALESCE(E.得意先略称,'') AS 得意先名
-- SQL_GET_ALL_NEW_KENSA_FROM
FROM ( SELECT DISTINCT a.管理No ,a.受注番号 ,a.枝番 ,a.品番 ,a.設変番号 ,a.納期 ,a.受注数 ,a.担当者コード ,a.受注区分 ,a.得意先コード FROM T_受注 AS a INNER JOIN T_発注 AS b ON b.管理No = a.管理No AND b.最終工程区分 = true INNER JOIN T_工程受入 AS c ON c.管理No = b.管理No AND c.工程順序No = b.工程順序No ) AS A LEFT OUTER JOIN ( SELECT 管理No ,MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS B ON B.管理No = A.管理No LEFT OUTER JOIN T_検査出荷依頼 AS C ON C.管理No = B.管理No AND C.分納No = B.分納No LEFT OUTER JOIN M_社員 AS D ON D.社員コード = A.担当者コード LEFT OUTER JOIN M_得意先 AS E ON E.得意先コード = A.得意先コード WHERE NOT EXISTS ( SELECT * FROM T_検査出荷依頼 WHERE 管理No = A.管理No AND (納入形態区分 IN ('1','2','4','11','12') OR (検査区分 =true AND 検査結果区分 = '0'))) AND EXISTS ( SELECT * FROM M_在庫 WHERE 品番 = A.品番 AND 設変番号 = A.設変番号 AND 仮受在庫数 > 0 )
-- SQL_GET_ALL_NEW_KENSA_ORDER
ORDER BY A.品番, A.設変番号, A.納期, A.受注番号
-- SQL_GET_ALL_NEW_SHUKKA_SELECT
SELECT A.管理No ,COALESCE(C.分納No,0) + 1 AS 分納No ,A.受注番号 ,A.枝番 ,A.品番 ,A.設変番号 ,A.納期 ,A.受注数 ,C.依頼日 ,C.依頼数 ,A.担当者コード ,COALESCE(D.社員名,'') AS 担当者名 ,CASE A.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分 ,A.得意先コード ,COALESCE(E.得意先略称,'') AS 得意先名
-- SQL_GET_ALL_NEW_SHUKKA_FROM
FROM ( SELECT a.管理No ,a.受注番号 ,a.枝番 ,a.品番 ,a.設変番号 ,a.納期 ,a.受注数 ,a.担当者コード ,a.受注区分 ,a.得意先コード FROM T_受注 AS a WHERE a.受注区分 IN ('2','3') ) AS A LEFT OUTER JOIN ( SELECT 管理No ,MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS B ON B.管理No = A.管理No LEFT OUTER JOIN T_検査出荷依頼 AS C ON C.管理No = B.管理No AND C.分納No = B.分納No LEFT OUTER JOIN M_社員 AS D ON D.社員コード = A.担当者コード LEFT OUTER JOIN M_得意先 AS E ON E.得意先コード = A.得意先コード WHERE NOT EXISTS ( SELECT * FROM T_検査出荷依頼 AS x WHERE x.管理No = A.管理No AND (x.納入形態区分 IN ('1','2','4','11','12') OR (検査区分 = true AND 検査結果区分 = '0') OR (出荷区分 <> '0' AND 検査区分 = false AND NOT EXISTS (SELECT * FROM T_売上 WHERE 管理No = x.管理No AND 分納No = x.分納No)))) AND EXISTS ( SELECT * FROM M_在庫 WHERE 品番 = A.品番 AND 設変番号 = A.設変番号 AND 在庫数 > 0)
-- SQL_GET_ALL_NEW_SHUKKA_ORDER
ORDER BY A.品番, A.設変番号, A.納期
-- SQL_GET_ALL_EDIT_SELECT
SELECT a.管理No ,a.分納No ,b.受注番号 ,b.枝番 ,b.品番 ,b.設変番号 ,b.納期 ,b.受注数 ,a.依頼日 ,a.依頼数 ,b.担当者コード ,COALESCE(c.社員名,'') AS 担当者名 ,CASE b.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分 ,b.得意先コード ,COALESCE(d.得意先略称,'') AS 得意先名
-- SQL_GET_ALL_EDIT_FROM
FROM T_検査出荷依頼 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード WHERE a.依頼日 BETWEEN CAST(? as DATE) AND CAST(? as DATE) AND ((a.検査区分 = true AND a.検査結果区分 = '0') OR (a.検査区分 = false AND NOT EXISTS (SELECT * FROM T_売上 WHERE 管理No = a.管理No AND 分納No = a.分納No)) )
-- SQL_GET_ALL_EDIT_FROM2
FROM T_検査出荷依頼 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード WHERE ((a.検査区分 = true AND a.検査結果区分 = '0') OR (a.検査区分 = false AND NOT EXISTS (SELECT * FROM T_売上 WHERE 管理No = a.管理No AND 分納No = a.分納No)) )
-- SQL_GET_ALL_EDIT_ORDER
ORDER BY a.依頼日 DESC, b.品番, b.設変番号, b.納期
-- SQL_MULTIPLE
SELECT CAST(値 as INT) FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ? AND Key3 = ?
-- SQL_GET_NEW_KENSA
SELECT a.管理No ,COALESCE(b.分納No,0) + 1 AS 分納No ,a.受注番号 ,a.枝番 ,a.得意先コード ,COALESCE(c.得意先名,'') AS 得意先名 ,a.品番 ,a.設変番号 ,a.品名 ,a.担当者コード ,COALESCE(d.社員名,'') AS 担当者名 ,a.受注区分 ,CASE a.受注区分 WHEN '1' THEN '先行手配 ' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分名 ,'0' AS 出荷区分 ,'' AS 振替受注番号 ,'' AS 振替枝番 ,0 AS 振替管理No ,1 AS 検査区分 ,COALESCE(e.在庫数,0) - COALESCE(e.出荷依頼数,0) AS 有効在庫数 ,COALESCE(e.在庫数,0) AS 在庫数 ,COALESCE(e.仮受在庫数,0) AS 仮受在庫数 ,COALESCE(e.出荷依頼数,0) AS 出荷依頼数 ,a.受注数 - (COALESCE(g.検査有完了数,0) + COALESCE(h.検査無依頼数,0) + COALESCE(f.納入数,0)) AS 受注残数 ,a.受注数 ,a.受注日 ,COALESCE(n.受入数計,0) - COALESCE(o.依頼数計,0) AS 生産数 ,COALESCE(l.作業区略称,'') AS 作業区名 ,k.受入日 ,COALESCE(n.受入数計,0) - COALESCE(o.依頼数計,0) AS 依頼数 ,a.単位 ,'11' AS 納入形態区分 ,a.納期 ,m.回答日 ,NULL AS 納入日 ,0 AS 検査成績書 ,e.梱包区分 ,'1' AS 出荷便区分 ,a.納入場所名 ,a.依頼備考1 ,a.依頼備考2 ,0 AS バージョン番号 FROM T_受注 AS a LEFT OUTER JOIN( SELECT 管理No, MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = a.得意先コード LEFT OUTER JOIN M_社員 AS d ON d.社員コード = a.担当者コード LEFT OUTER JOIN M_在庫 AS e ON e.品番 = a.品番 AND e.設変番号 = a.設変番号 LEFT OUTER JOIN ( /* 出荷有りの完了数 */ SELECT x.管理No, SUM(x.依頼数) AS 納入数 FROM T_売上 AS x INNER JOIN T_検査出荷依頼 AS y ON y.管理No = x.管理No AND y.分納No = x.分納No AND y.出荷区分 <> '0' GROUP BY x.管理No ) AS f ON f.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査有りの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査有完了数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = true AND 検査結果区分 <> '0' GROUP BY 管理No ) AS g ON g.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査無しの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査無依頼数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = false GROUP BY 管理No ) AS h ON h.管理No = a.管理No LEFT OUTER JOIN T_発注 AS i ON i.管理No = a.管理No AND i.最終工程区分 = true LEFT OUTER JOIN ( SELECT 管理No, 工程順序No, MAX(分納No) AS 分納No FROM T_工程受入 GROUP BY 管理No, 工程順序No ) AS j ON j.管理No = i.管理No AND j.工程順序No = i.工程順序No LEFT OUTER JOIN T_工程受入 AS k ON k.管理No = i.管理No AND k.工程順序No = i.工程順序No AND k.分納No = j.分納No LEFT OUTER JOIN M_作業区仕入先 AS l ON l.作業区コード = i.作業区コード LEFT OUTER JOIN ( SELECT 管理No, 工程順序No, SUM(受入数) AS 受入数計 FROM T_工程受入 GROUP BY 管理No, 工程順序No ) AS n ON n.管理No = i.管理No AND n.工程順序No = i.工程順序No LEFT OUTER JOIN ( SELECT 管理No, SUM(依頼数) AS 依頼数計 FROM T_検査出荷依頼 WHERE 出荷区分 IN ('0','3') GROUP BY 管理No ) AS o ON o.管理No = i.管理No LEFT OUTER JOIN T_納期回答 AS m ON m.管理No = a.管理No AND m.分納No = COALESCE(b.分納No,0) + 1 WHERE a.管理No = CAST(? as INT)
-- SQL_GET_NEW_SHUKKA
SELECT a.管理No ,COALESCE(b.分納No,0) + 1 AS 分納No ,a.受注番号 ,a.枝番 ,a.得意先コード ,COALESCE(c.得意先名,'') AS 得意先名 ,a.品番 ,a.設変番号 ,a.品名 ,a.担当者コード ,COALESCE(d.社員名,'') AS 担当者名 ,a.受注区分 ,CASE a.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分名 ,'1' AS 出荷区分 ,'' AS 振替受注番号 ,'' AS 振替枝番 ,0 AS 振替管理No ,0 AS 検査区分 ,COALESCE(e.在庫数,0) - COALESCE(e.出荷依頼数,0) AS 有効在庫数 ,COALESCE(e.在庫数,0) AS 在庫数 ,COALESCE(e.仮受在庫数,0) AS 仮受在庫数 ,COALESCE(e.出荷依頼数,0) AS 出荷依頼数 ,a.受注数 - (COALESCE(g.検査有完了数,0) + COALESCE(h.検査無依頼数,0) + COALESCE(f.納入数,0)) AS 受注残数 ,a.受注数 ,a.受注日 ,0 AS 生産数 ,'' AS 作業区名 ,NULL AS 受入日 ,0 AS 依頼数 ,a.単位 ,'1' AS 納入形態区分 ,a.納期 ,m.回答日 ,NULL AS 納入日 ,0 AS 検査成績書 ,e.梱包区分 ,'1' AS 出荷便区分 ,a.納入場所名 ,a.依頼備考1 ,a.依頼備考2 ,0 AS バージョン番号 FROM T_受注 AS a LEFT OUTER JOIN( SELECT 管理No, MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = a.得意先コード LEFT OUTER JOIN M_社員 AS d ON d.社員コード = a.担当者コード LEFT OUTER JOIN M_在庫 AS e ON e.品番 = a.品番 AND e.設変番号 = a.設変番号 LEFT OUTER JOIN ( /* 出荷有りの完了数 */ SELECT x.管理No, SUM(x.依頼数) AS 納入数 FROM T_売上 AS x INNER JOIN T_検査出荷依頼 AS y ON y.管理No = x.管理No AND y.分納No = x.分納No AND y.出荷区分 <> '0' GROUP BY x.管理No ) AS f ON f.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査有りの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査有完了数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = true AND 検査結果区分 <> '0' GROUP BY 管理No ) AS g ON g.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査無しの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査無依頼数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = false GROUP BY 管理No ) AS h ON h.管理No = a.管理No LEFT OUTER JOIN T_納期回答 AS m ON m.管理No = a.管理No AND m.分納No = COALESCE(b.分納No,0) + 1 WHERE a.管理No = CAST(? as INT)
-- SQL_GET_EDIT
SELECT a.管理No ,a.分納No ,b.受注番号 ,b.枝番 ,b.得意先コード ,COALESCE(c.得意先名,'') AS 得意先名 ,b.品番 ,b.設変番号 ,b.品名 ,b.担当者コード ,COALESCE(d.社員名,'') AS 担当者名 ,b.受注区分 ,CASE b.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' ELSE '再納' END AS 受注区分名 ,a.出荷区分 ,a.振替受注番号 ,a.振替枝番 ,a.振替管理No ,a.検査区分 ,COALESCE(e.在庫数,0) - COALESCE(e.出荷依頼数,0) AS 有効在庫数 ,COALESCE(e.在庫数,0) AS 在庫数 ,COALESCE(e.仮受在庫数,0) AS 仮受在庫数 ,COALESCE(e.出荷依頼数,0) AS 出荷依頼数 ,b.受注数 - (COALESCE(g.検査有完了数,0) + COALESCE(h.検査無依頼数,0) + COALESCE(f.納入数,0)) AS 受注残数 ,b.受注数 ,b.受注日 ,a.生産数 ,COALESCE(l.作業区略称,'') AS 作業区名 ,k.受入日 ,a.依頼数 ,b.単位 ,a.納入形態区分 ,b.納期 ,a.回答日 ,a.納入日 ,a.検査成績書 ,a.梱包区分 ,a.出荷便区分 ,a.納入場所名 ,a.備考1 ,a.備考2 ,a.バージョン番号 FROM T_検査出荷依頼 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = b.得意先コード LEFT OUTER JOIN M_社員 AS d ON d.社員コード = b.担当者コード LEFT OUTER JOIN M_在庫 AS e ON e.品番 = b.品番 AND e.設変番号 = b.設変番号 LEFT OUTER JOIN ( /* 出荷有りの完了数 */ SELECT x.管理No, SUM(x.依頼数) AS 納入数 FROM T_売上 AS x INNER JOIN T_検査出荷依頼 AS y ON y.管理No = x.管理No AND y.分納No = x.分納No AND y.出荷区分 <> '0' GROUP BY x.管理No ) AS f ON f.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査有りの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査有完了数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = true AND 検査結果区分 <> '0' GROUP BY 管理No ) AS g ON g.管理No = a.管理No LEFT OUTER JOIN ( /* 出荷無し/検査無しの完了数 */ SELECT 管理No, SUM(依頼数) AS 検査無依頼数 FROM T_検査出荷依頼 WHERE 出荷区分 = '0' AND 検査区分 = false AND 分納No <> CAST(? as INT) GROUP BY 管理No ) AS h ON h.管理No = a.管理No LEFT OUTER JOIN T_発注 AS i ON i.管理No = (CASE WHEN a.振替管理No = 0 THEN a.管理No ELSE a.振替管理No END) AND i.最終工程区分 = true LEFT OUTER JOIN ( SELECT 管理No, 工程順序No, MAX(分納No) AS 分納No FROM T_工程受入 GROUP BY 管理No, 工程順序No ) AS j ON j.管理No = i.管理No AND j.工程順序No = i.工程順序No LEFT OUTER JOIN T_工程受入 AS k ON k.管理No = i.管理No AND k.工程順序No = i.工程順序No AND k.分納No = j.分納No LEFT OUTER JOIN M_作業区仕入先 AS l ON l.作業区コード = i.作業区コード WHERE a.管理No = CAST(? as INT) AND a.分納No = CAST(? as INT)
-- SQL_GET_ACCEPT
SELECT a.管理No ,a.受注番号 ,a.枝番 ,a.品番 ,a.設変番号 ,COALESCE(g.生産数,0) AS 生産数 ,COALESCE(e.作業区略称,'') AS 作業区名 ,d.受入日 ,CASE WHEN g.生産数 IS NULL THEN 0 ELSE 1 END AS 依頼中判定 FROM T_受注 AS a INNER JOIN T_発注 AS b ON b.管理No = a.管理No AND b.最終工程区分 = true INNER JOIN ( SELECT 管理No, 工程順序No, MAX(分納No) AS 分納No FROM T_工程受入 GROUP BY 管理No, 工程順序No ) AS c ON c.管理No = b.管理No AND c.工程順序No = b.工程順序No INNER JOIN T_工程受入 AS d ON d.管理No = c.管理No AND d.工程順序No = c.工程順序No AND d.分納No = c.分納No LEFT OUTER JOIN ( SELECT 管理No, MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS f ON f.管理No = a.管理No LEFT OUTER JOIN ( SELECT 管理No, 分納No, 生産数 FROM T_検査出荷依頼 WHERE 検査区分 = false OR (検査区分 = true AND 検査結果区分 = '0') ) AS g ON g.管理No = f.管理No AND g.分納No = f.分納No LEFT OUTER JOIN M_作業区仕入先 AS e ON e.作業区コード = b.作業区コード WHERE a.受注区分 IN ('1','4') AND a.受注番号 &@ ? AND LENGTH(a.受注番号) = LENGTH(?) AND a.枝番 = ?
-- SQL_CHECK_EXISTS_REQUEST
SELECT CASE WHEN EXISTS (SELECT * FROM T_検査出荷依頼 WHERE 管理No = CAST(? as INT) AND 検査区分 = true AND 検査結果区分 IN ('1','2') AND 納入形態区分 IN ('1','2','4','11','12') ) THEN 1 /* 完了依頼有り */ ELSE CASE WHEN EXISTS (SELECT * FROM T_売上 WHERE 管理No = CAST(? as INT) AND 納入形態区分 IN ('1','2','4') ) THEN 1 /* 完了依頼有り */ ELSE 0 /* 完了依頼無し */ END END AS 判定
-- SQL_GET_LAST_TIME_DELIVERY
SELECT MAX(納入日) AS 納入日 FROM T_検査出荷依頼 WHERE 管理No = CAST(? as INT) AND 分納No <> CAST(? as INT)

