-- SQL_GETALL_CORE
SELECT a.管理No,a.分納No,b.受注番号,b.枝番,b.品番,b.設変番号,a.納入日,a.依頼数,a.結果登録日,NULL AS 売上登録日,'－' AS SMC現品票出力日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,CASE WHEN b.得意先コード = '1' THEN '1' ELSE '0' END AS 得意先区分 FROM T_検査出荷依頼 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード WHERE a.出荷区分 IN ('1','2','3') AND (a.検査区分 = false OR (a.検査区分 = true AND a.検査結果区分 = '1')) AND NOT EXISTS (SELECT * FROM T_売上 WHERE 管理No = a.管理No AND 分納No = a.分納No)
-- SQL_GETALL_ZYUCHUUBANGOU
AND b.受注番号 &@ ? AND LENGTH(b.受注番号) = LENGTH(?)
-- SQL_GETALL_TANTOUSYA
AND b.担当者コード = ?
-- SQL_GETALL_ORDER_BY
ORDER BY b.品番, b.設変番号, a.納入日
-- SQL_GETALL_UPDATE_CORE
SELECT a.管理No,a.分納No,b.受注番号,b.枝番,b.品番,b.設変番号,a.納入日,a.依頼数,d.結果登録日,a.登録日,CASE WHEN e.印刷日 IS NULL THEN '－' ELSE TO_CHAR(e.印刷日, 'YYYY/MM/DD') END AS 印刷日,b.担当者コード,COALESCE(c.社員名,'') AS 担当者名,CASE WHEN b.得意先コード = '1' THEN '1' ELSE '0' END AS 得意先区分 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_社員 AS c ON c.社員コード = b.担当者コード INNER JOIN T_検査出荷依頼 AS d ON d.管理No = a.管理No AND d.分納No = a.分納No AND d.出荷区分 IN ('1','2','3') LEFT OUTER JOIN ( SELECT 管理No ,分納No ,MAX(印刷日) AS 印刷日 FROM T_現品票 GROUP BY 管理No,分納No ) AS e ON e.管理No = a.管理No AND e.分納No = a.分納No WHERE a.登録日 BETWEEN CAST(CASE WHEN ? = '' THEN '2000-01-01' ELSE ? END as DATE) AND CAST(CASE WHEN ? = '' THEN '9999-12-31' ELSE ? END as DATE)
-- SQL_GET_NEW_CORE
SELECT a.管理No ,a.分納No ,b.受注番号 ,b.枝番 ,b.得意先コード ,COALESCE(c.得意先名,'') AS 得意先名 ,CASE WHEN b.得意先コード = '1' THEN '1' ELSE '0' END AS 得意先区分 ,b.品番 ,b.設変番号 ,b.品名 ,b.客先品番 ,b.担当者コード ,COALESCE(d.社員名,'') AS 担当者名 ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.管理番号,'') WHEN 'K' THEN COALESCE(f.管理番号,'') WHEN 'C' THEN COALESCE(f.管理番号,'') ELSE '' END AS 管理番号 ,b.請求元 ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.工号,'') WHEN 'K' THEN COALESCE(f.工号,'') WHEN 'C' THEN COALESCE(f.工号,'') ELSE '' END AS 工号 ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.棚番,'') WHEN 'K' THEN COALESCE(f.棚番,'') WHEN 'C' THEN COALESCE(f.棚番,'') ELSE '' END AS 棚番 ,b.受注日 ,b.納期 ,a.納入日 ,b.受注数 ,a.依頼数 ,CASE a.納入形態区分 WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' WHEN '4' THEN '過剰納入' WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE '' END AS 納入形態 ,a.依頼数 AS 納入数 ,b.単位 ,b.単価 ,CASE COALESCE(c.金額端数処理区分,'1') WHEN '1' THEN CAST(FLOOR(b.単価 * a.依頼数) as BIGINT) WHEN '2' THEN CAST(CEIL(b.単価 * a.依頼数) as BIGINT) ELSE CAST(ROUND(b.単価 * a.依頼数, 0) as BIGINT) END AS 金額 ,b.次工程名 ,a.納入場所名 ,'' AS 現品票備考 ,b.納入備考1 ,b.納入備考2 ,'1' AS 梱包単位 ,1 AS バージョン番号 ,a.納入形態区分 ,NULL AS SeqNo ,NULL AS 個数 ,NULL AS 梱包数 FROM T_検査出荷依頼 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = b.得意先コード LEFT OUTER JOIN M_社員 AS d ON d.社員コード = b.担当者コード LEFT OUTER JOIN T_購買伝票受注 AS e ON e.帳票番号 = b.注文バーコード番号 LEFT OUTER JOIN T_工号生産納入指示 AS f ON f.発行連番 = b.注文バーコード番号 WHERE a.管理No = CAST(? as INT) AND a.分納No = CAST(? as INT)
-- SQL_GET_TEISEI_CORE
SELECT a.管理No,a.分納No,b.受注番号,b.枝番,b.得意先コード,COALESCE(c.得意先名,'') AS 得意先名,CASE WHEN b.得意先コード = '1' THEN '1' ELSE '0' END AS 得意先区分,b.品番,b.設変番号,b.品名,b.客先品番,b.担当者コード,COALESCE(d.社員名,'') AS 担当者名,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.管理番号,'') WHEN 'K' THEN COALESCE(f.管理番号,'') WHEN 'C' THEN COALESCE(f.管理番号,'') ELSE ''END AS 管理番号 ,b.請求元,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.工号,'') WHEN 'K' THEN COALESCE(f.工号,'') WHEN 'C' THEN COALESCE(f.工号,'') ELSE ''END AS 工号,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(e.棚番,'') WHEN 'K' THEN COALESCE(f.棚番,'') WHEN 'C' THEN COALESCE(f.棚番,'') ELSE ''END AS 棚番,b.受注日,b.納期,a.納入日,b.受注数,g.依頼数,CASE a.納入形態区分 WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' WHEN '4' THEN '過剰納入' WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE ''END AS 納入形態,a.依頼数 AS 納入数,b.単位,b.単価,CASE COALESCE(c.金額端数処理区分,'1') WHEN '1' THEN CAST(FLOOR(b.単価 * a.依頼数) as BIGINT) WHEN '2' THEN CAST(CEIL(b.単価 * a.依頼数) as BIGINT) ELSE CAST(ROUND(b.単価 * a.依頼数, 0) as BIGINT)END AS 金額,b.次工程名,g.納入場所名,a.現品票備考,a.備考1,a.備考2,a.梱包単位,a.バージョン番号,a.納入形態区分,h.SeqNo,h.個数,h.梱包数 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = b.得意先コード LEFT OUTER JOIN M_社員 AS d ON d.社員コード = b.担当者コード LEFT OUTER JOIN T_購買伝票受注 AS e ON e.帳票番号 = b.注文バーコード番号 LEFT OUTER JOIN T_工号生産納入指示 AS f ON f.発行連番 = b.注文バーコード番号 INNER JOIN T_検査出荷依頼 AS g ON g.管理No = a.管理No AND g.分納No = a.分納No INNER JOIN T_売上詳細 AS h ON h.管理No = a.管理No AND h.分納No = a.分納No WHERE a.管理No = CAST(? as INT) AND a.分納No = CAST(? as INT) ORDER BY h.SeqNo
-- SQL_NOUHINSYO
SELECT a.管理No,a.分納No,b.得意先コード,COALESCE(c.郵便番号1,'') AS 郵便番号1,COALESCE(c.郵便番号2,'') AS 郵便番号2,COALESCE(c.住所1,'') AS 住所1,COALESCE(c.住所2,'') AS 住所2,COALESCE(c.得意先名,'') AS 得意先名,b.受注番号,b.受注日,b.納期,a.納入日,CASE d.出荷便区分 WHEN '1' THEN '赤帽便' WHEN '2' THEN 'ヤマト便' WHEN '3' THEN '佐川急便' WHEN '4' THEN '営業届け' WHEN '5' THEN 'その他' ELSE '' END AS 出荷便,CASE WHEN COALESCE(c.締日区分,false) = true THEN '末日' ELSE COALESCE(c.締日,'') || '日' END AS 締日 ,b.品番,b.設変番号,b.品名,b.受注数,a.依頼数 AS 納入数,b.単位,CASE a.納入形態区分 WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' ELSE '過剰納入' END AS 納入形態,a.単価,a.金額,d.納入場所名,a.備考1,a.備考2,e.個数,e.梱包数 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_得意先 AS c ON c.得意先コード = b.得意先コード INNER JOIN T_検査出荷依頼 AS d ON d.管理No = a.管理No AND d.分納No = a.分納No INNER JOIN T_売上詳細 AS e ON e.管理No = a.管理No AND e.分納No = a.分納No WHERE a.管理No = ? AND a.分納No = ? ORDER BY e.SeqNo
-- SQL_SMC_JUDGE
SELECT CASE WHEN 得意先コード = '1' THEN 1 ELSE 0 END AS 判定 FROM T_受注 WHERE 管理No = CAST(? as INT)
-- SQL_GENPINHYOU_SMC
SELECT a.管理No,a.分納No,a.納入日,b.請求元,b.受注番号,CASE WHEN b.客先品番 = '' THEN b.品番 ELSE b.客先品番 END AS 品番,b.設変番号,b.品名,b.次工程名,e.納入場所名,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(c.棚番,'') WHEN 'K' THEN COALESCE(d.棚番,'') WHEN 'C' THEN COALESCE(d.棚番,'') ELSE ''END AS 棚番,CASE b.注文データ区分 WHEN 'A' THEN CASE WHEN LENGTH(COALESCE(c.管理番号,'')) < 15 THEN SUBSTRING(COALESCE(c.管理番号,''), 4, 15) ELSE COALESCE(c.工号,'') END WHEN 'K' THEN COALESCE(d.工号,'') WHEN 'C' THEN COALESCE(d.工号,'') ELSE ''END AS 工号,g.個数計,g.梱包数計,CASE WHEN a.梱包単位 = '1' THEN '箱' ELSE '袋' END AS 梱包単位,f.個数,f.梱包数,b.テーパーおねじ区分 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN T_購買伝票受注 AS c ON c.帳票番号 = b.注文バーコード番号 LEFT OUTER JOIN T_工号生産納入指示 AS d ON d.発行連番 = b.注文バーコード番号 INNER JOIN T_検査出荷依頼 AS e ON e.管理No = a.管理No AND e.分納No = a.分納No INNER JOIN T_売上詳細 AS f ON f.管理No = a.管理No AND f.分納No = a.分納No INNER JOIN ( SELECT 管理No ,分納No ,SUM(個数 * 梱包数) AS 個数計 ,SUM(梱包数) AS 梱包数計 FROM T_売上詳細 GROUP BY 管理No, 分納No ) AS g ON g.管理No = a.管理No AND g.分納No = a.分納No WHERE a.管理No = CAST(? as INT) AND a.分納No = CAST(? as INT) ORDER BY f.SeqNo
-- SQL_GENPINHYOU_ZISYA
SELECT a.管理No ,a.分納No ,a.納入日 ,b.受注番号 ,CASE WHEN b.客先品番 = '' THEN b.品番 ELSE b.客先品番 END AS 品番 ,b.設変番号 ,b.品名 ,c.納入場所名 ,a.現品票備考 ,e.個数計 ,e.梱包数計 ,CASE WHEN a.梱包単位 = '1' THEN '箱' ELSE '袋' END AS 梱包単位 ,d.個数 ,d.梱包数 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No INNER JOIN T_検査出荷依頼 AS c ON c.管理No = a.管理No AND c.分納No = a.分納No INNER JOIN T_売上詳細 AS d ON d.管理No = a.管理No AND d.分納No = a.分納No INNER JOIN ( SELECT 管理No ,分納No ,SUM(個数 * 梱包数) AS 個数計 ,SUM(梱包数) AS 梱包数計 FROM T_売上詳細 GROUP BY 管理No, 分納No ) AS e ON e.管理No = a.管理No AND e.分納No = a.分納No WHERE a.管理No = CAST(? as INT) AND a.分納No = CAST(? as INT) ORDER BY d.SeqNo
-- SQL_GET_GENPINHYOU_PARAM
SELECT 値 FROM M_パラメータ WHERE Key1 = '10' AND Key2 = 'H22' AND Key3 in ('1','2') ORDER BY Key3
-- SQL_SMC_GENPINHYOU
SELECT a.管理No ,a.分納No ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(c.現品票フォーム区分,'') WHEN 'K' THEN COALESCE(d.現品票フォーム区分,'') WHEN 'C' THEN COALESCE(d.現品票フォーム区分,'') ELSE '' END AS 現品票フォーム区分 ,CASE WHEN b.客先品番 = '' THEN b.品番 ELSE b.客先品番 END AS 品番 ,e.個数 AS 入数 ,e.梱包数 AS 箱数 ,f.出荷数 ,f.全箱数 ,b.納入場所名 ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(c.棚番,'') WHEN 'K' THEN COALESCE(d.棚番,'') WHEN 'C' THEN COALESCE(d.棚番,'') ELSE '' END AS 棚番 ,CASE WHEN STRPOS(b.納入場所名,'部品中継') <> 0 THEN '1' WHEN b.注文データ区分 = 'A' THEN COALESCE(c.中継有無,'') WHEN b.注文データ区分 IN ('K','C') THEN COALESCE(d.中継有無,'') ELSE '' END AS 中継有無 ,b.次工程名 ,b.品名 ,b.設変番号 ,a.納入日 ,b.請求元 ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(c.手配No,'') ELSE '' END AS 手配No ,CASE b.注文データ区分 WHEN 'A' THEN COALESCE(c.注文番号,'') WHEN 'K' THEN COALESCE(d.発行連番,'') WHEN 'C' THEN COALESCE(d.発行連番,'') ELSE '' END AS 注番 ,CASE b.注文データ区分 WHEN 'A' THEN CASE WHEN LENGTH(COALESCE(c.管理番号,'')) < 15 THEN SUBSTRING(COALESCE(c.管理番号,''), 4, 15) ELSE CASE WHEN LENGTH(RTRIM(COALESCE(c.工号,''))) = 0 THEN COALESCE(c.仕込NO,'') ELSE COALESCE(c.工号,'') END END WHEN 'K' THEN COALESCE(d.工号,'') WHEN 'C' THEN COALESCE(d.工号,'') ELSE '' END AS 工号 ,b.テーパーおねじ区分 ,CASE b.注文データ区分 WHEN 'A' THEN RIGHT(COALESCE(c.注文番号,''),3) WHEN 'K' THEN RIGHT(COALESCE(d.発行連番,''),3) WHEN 'C' THEN RIGHT(COALESCE(d.発行連番,''),3) ELSE '' END AS 注番2 ,CASE b.注文データ区分 WHEN 'A' THEN LEFT(COALESCE(c.帳票番号,''), 8) WHEN 'K' THEN COALESCE(d.発行連番,'') WHEN 'C' THEN COALESCE(d.発行連番,'') ELSE '' END AS 帳票番号 ,CASE b.注文データ区分 WHEN 'A' THEN RIGHT(COALESCE(c.帳票番号,''), 2) WHEN 'K' THEN '01' WHEN 'C' THEN '01' ELSE '' END AS 帳票番号追番 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No LEFT OUTER JOIN T_購買伝票受注 AS c ON c.帳票番号 = b.注文バーコード番号 LEFT OUTER JOIN T_工号生産納入指示 AS d ON d.発行連番 = b.注文バーコード番号 INNER JOIN T_売上詳細 AS e ON e.管理No = a.管理No AND e.分納No = a.分納No INNER JOIN ( SELECT 管理No ,分納No ,SUM(個数 * 梱包数) AS 出荷数 ,SUM(梱包数) AS 全箱数 FROM T_売上詳細 GROUP BY 管理No, 分納No ) AS f ON f.管理No = a.管理No AND f.分納No = a.分納No WHERE (a.管理No = ? AND a.分納No = ?)
-- SQL_SMC_GENPINHYOU_WHERE
OR (a.管理No = ? AND a.分納No = ?)
-- SQL_SMC_GENPINHYOU_ORDER
ORDER BY 現品票フォーム区分, b.品番, b.設変番号, a.管理No, a.分納No, e.SeqNo

