-- SQL_GET_ALL_COUNT
SELECT CAST(COUNT(a.管理No) AS INT)
-- SQL_GET_ALL
SELECT a.管理No ,a.受注番号 ,a.枝番 ,a.品番 ,a.設変番号 ,a.受注日 ,a.納期 ,CASE a.受注区分 WHEN '1' THEN '1' /* 先行手配 */ WHEN '2' THEN '0' /* 受注（計画無し） */ WHEN '3' THEN '1' /* 受注（計画有り） */ ELSE '1' /* 再納 */ END AS 生産数表示 ,COALESCE(b.生産数,0) AS 生産数 ,CASE a.受注区分 WHEN '1' THEN '0' /* 先行手配 */ WHEN '2' THEN '1' /* 受注（計画無し） */ WHEN '3' THEN '1' /* 受注（計画有り） */ ELSE '0' /* 再納 */ END AS 受注数表示 ,a.受注数 ,CASE WHEN a.受注区分 IN ('1','4') /* 先行手配, 再納 */ THEN CASE WHEN d.管理No IS NULL /* 依頼無し */ THEN '' /* 依頼有り */ ELSE CASE WHEN d.検査区分 = false /* 検査無し */ THEN CASE d.納入形態区分 WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE '??' END /* 検査有り */ ELSE CASE d.検査結果区分 /* 未検査 */ WHEN '0' THEN '依頼中' /* 合格 */ WHEN '1' THEN CASE d.納入形態区分 WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE '' END /* 不合格 */ WHEN '2' THEN '不合格' ELSE '??' END END END /* 受注（計画無し）,受注（計画有り）,再納 */ ELSE CASE WHEN d.管理No IS NULL /* 依頼無し */ THEN '' /* 依頼有り */ ELSE CASE WHEN d.検査結果区分 = '2' /* 不合格 */ THEN '不合格' /* 不合格以外 */ ELSE CASE WHEN e.管理No IS NULL /* 売上無し */ THEN '依頼中' /* 売上有り */ ELSE CASE e.納入形態区分 WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' WHEN '4' THEN '過剰納入' ELSE '??' END END END END END AS 状況 ,CASE WHEN a.受注区分 IN ('1','4') /* 先行手配, 再納 */ THEN CASE WHEN d.管理No IS NULL /* 依頼無し */ THEN NULL /* 依頼有り */ ELSE CASE WHEN d.検査区分 = false /* 検査無し */ THEN CASE d.納入形態区分 WHEN '11' THEN d.依頼日 WHEN '12' THEN d.依頼日 WHEN '13' THEN NULL ELSE NULL END /* 検査有り */ ELSE CASE d.検査結果区分 /* 未検査 */ WHEN '0' THEN NULL /* 合格 */ WHEN '1' THEN CASE d.納入形態区分 WHEN '11' THEN d.結果登録日 WHEN '12' THEN d.結果登録日 WHEN '13' THEN NULL ELSE NULL END /* 不合格 */ WHEN '2' THEN d.結果登録日 ELSE NULL END END END /* 受注（計画無し）,受注（計画有り）,再納 */ ELSE CASE WHEN d.管理No IS NULL /* 依頼無し */ THEN NULL /* 依頼有り */ ELSE CASE WHEN d.検査結果区分 = '2' /* 不合格 */ THEN d.結果登録日 /* 不合格以外 */ ELSE CASE WHEN e.管理No IS NULL /* 売上無し */ THEN NULL /* 売上有り */ ELSE CASE e.納入形態区分 WHEN '1' THEN e.納入日 WHEN '2' THEN e.納入日 WHEN '3' THEN NULL WHEN '4' THEN e.納入日 ELSE NULL END END END END END AS 完了日 ,a.担当者コード ,COALESCE(f.社員名,'') AS 担当者名 ,a.得意先コード ,CASE WHEN a.得意先コード = '1' THEN '1' ELSE '0' END as 得意先区分 ,CASE WHEN a.注文データ区分 = '' THEN '0' /* 伝送以外(black) */ ELSE CASE WHEN a.データ更新区分 = false THEN '1' /* 未更新(red) */ ELSE '2' /* 更新済み(blue) */ END END AS 色区分 ,d.依頼日
-- SQL_GET_ALL_FROM_CLAUSE
FROM T_受注 AS a LEFT OUTER JOIN T_生産計画 AS b ON b.管理No = a.管理No LEFT OUTER JOIN ( SELECT 管理No, MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS c ON c.管理No = a.管理No LEFT OUTER JOIN T_検査出荷依頼 AS d ON d.管理No = c.管理No AND d.分納No = c.分納No LEFT OUTER JOIN T_売上 AS e ON e.管理No = d.管理No AND e.分納No = d.分納No LEFT OUTER JOIN M_社員 AS f ON f.社員コード = a.担当者コード
-- SQL_GET_ALL_WHERE_CLAUSE_ORDER_NO
WHERE a.受注番号 &@ ? AND LENGTH(a.受注番号) = LENGTH(?) /*「受注番号」指定時 */
-- SQL_GET_ALL_WHERE_CLAUSE_PARTS_NO
WHERE a.品番 &@ ? AND LENGTH(a.品番) = LENGTH(?) /*「品番」指定時 */
-- SQL_GET_ALL_WHERE_CLAUSE_SETTING_NO
AND a.設変番号 = ? /*「設変番号」も同時に指定時 */
-- SQL_GET_ALL_ORDER_BY_CLAUSE
ORDER BY a.納期 DESC, a.受注番号 DESC, a.枝番 DESC
-- SQL_MULTIPLE
SELECT CAST(値 as INT) FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ? AND Key3 = ?
-- SQL_GET_STOCK
SELECT 品番 ,設変番号 ,在庫数 ,仮受在庫数 ,出荷依頼数 ,在庫数 - 出荷依頼数 AS 有効在庫数 FROM M_在庫 WHERE 品番 = ? AND 設変番号 = ?
-- SQL_GET_MEMO
SELECT 工号 ,四半期予定数 ,年度予定数 ,納期 FROM M_納入メモ WHERE 工号 = ? AND CURRENT_DATE BETWEEN 有効開始日 AND 有効終了日
-- SQL_GET_NON_WORKING_DAYS
SELECT 非稼働日 FROM M_カレンダー WHERE 非稼働日 BETWEEN CAST(? as DATE) AND CAST(? as DATE) ORDER BY 非稼働日
-- SQL_GET_ORDER_QUANTITY
SELECT FLOOR(COALESCE(a.受注数,0) / 6) AS 月平均 ,COALESCE(b.受注数,0) AS 年合計 FROM ( SELECT SUM(受注数) AS 受注数 FROM T_受注 WHERE 納期 BETWEEN CURRENT_DATE - interval '6 month' AND CURRENT_DATE - interval '1 day' AND 受注区分 IN ('2','3') AND LEFT(受注番号,8) = ? ) AS a CROSS JOIN ( SELECT SUM(受注数) AS 受注数 FROM T_受注 WHERE 納期 BETWEEN CURRENT_DATE - interval '1 year' AND CURRENT_DATE - interval '1 day' AND 受注区分 IN ('2','3') AND LEFT(受注番号,8) = ? ) AS b
-- SQL_GET_ORDER
SELECT a.管理No ,a.受注番号 ,a.枝番 ,a.得意先コード ,COALESCE(b.得意先名,'') AS 得意先名 ,CASE WHEN a.得意先コード = '1' THEN '1' ELSE '0' END as 得意先区分 ,CASE a.受注区分 WHEN '1' THEN '先行手配' WHEN '2' THEN '受注' WHEN '3' THEN '受注' WHEN '4' THEN '再納' ELSE '' END AS 受注区分 ,a.品番 ,a.設変番号 ,a.品名 ,CASE WHEN i.品番 IS NULL THEN '' ELSE '管理図面' END AS 図面分類 ,a.客先品番 ,a.受注日 ,a.納期 ,CASE WHEN a.注文データ区分 = 'A' THEN COALESCE(c.営業納期,'') ELSE '' END AS 営業納期 ,a.受注数 ,CASE WHEN a.受注区分 IN ('1', '4') THEN a.受注数 - COALESCE(d.完了数,0) ELSE a.受注数 - COALESCE(e.納入数,0) END AS 受注残数 ,CASE WHEN a.受注区分 IN ('1', '4') /* 先行手配 */ THEN CASE WHEN g.管理No IS NULL /* 依頼無し */ THEN '' /* 依頼有り */ ELSE CASE WHEN g.検査区分 = false /* 検査無し */ THEN CASE g.納入形態区分 WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE '' END /* 検査有り */ ELSE CASE g.検査結果区分 /* 未検査 */ WHEN '0' THEN '' /* 合格 */ WHEN '1' THEN CASE g.納入形態区分 WHEN '11' THEN 'END' WHEN '12' THEN 'STP' WHEN '13' THEN 'ING' ELSE '' END /* 不合格 */ WHEN '2' THEN '不合格' ELSE '' END END END /* 受注（計画無し）,受注（計画有り）,再納 */ ELSE CASE WHEN g.管理No IS NULL /* 依頼無し */ THEN '' /* 依頼有り */ ELSE CASE WHEN g.検査結果区分 = '2' /* 不合格 */ THEN '不合格' /* 不合格以外 */ ELSE CASE WHEN h.管理No IS NULL /* 売上無し */ THEN '' /* 売上有り */ ELSE CASE h.納入形態区分 WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' WHEN '4' THEN '過剰納入' ELSE '' END END END END END AS 納入形態 ,j.登録日 AS 回答メール送信日 ,COALESCE(k.在庫数,0) AS 在庫数 ,COALESCE(k.仮受在庫数,0) AS 仮受在庫数 ,COALESCE(k.在庫数,0) - COALESCE(k.出荷依頼数,0) AS 有効在庫数 ,a.担当者コード ,COALESCE(l.社員名,'') AS 担当者名 ,m.発注日 ,m.発注数 ,a.納入場所名 FROM T_受注 AS a LEFT OUTER JOIN M_得意先 AS b ON b.得意先コード = a.得意先コード LEFT OUTER JOIN T_購買伝票受注 AS c ON c.帳票番号 = a.注文バーコード番号 LEFT OUTER JOIN ( SELECT 管理No, SUM(依頼数) AS 完了数 FROM T_検査出荷依頼 WHERE 検査区分 = false OR (検査区分 = true AND 検査結果区分 = '1') /* 検査無し、合格 */ GROUP BY 管理No ) AS d ON d.管理No = a.管理No LEFT OUTER JOIN ( SELECT 管理No, SUM(依頼数) AS 納入数 FROM T_売上 GROUP BY 管理No ) AS e ON e.管理No = a.管理No LEFT OUTER JOIN ( SELECT 管理No, MAX(分納No) AS 分納No FROM T_検査出荷依頼 GROUP BY 管理No ) AS f ON f.管理No = a.管理No LEFT OUTER JOIN T_検査出荷依頼 AS g ON g.管理No = f.管理No AND g.分納No = f.分納No LEFT OUTER JOIN T_売上 AS h ON h.管理No = g.管理No AND h.分納No = g.分納No LEFT OUTER JOIN ( SELECT DISTINCT 品番 FROM T_図面 WHERE 図面種類 = '1' ) AS i ON i.品番 = a.品番 LEFT OUTER JOIN ( SELECT 管理No, MAX(登録日) AS 登録日 FROM T_納期回答メール GROUP BY 管理No ) AS j ON j.管理No = a.管理No LEFT OUTER JOIN M_在庫 AS k ON k.品番 = a.品番 AND k.設変番号 = a.設変番号 LEFT OUTER JOIN M_社員 AS l ON l.社員コード = a.担当者コード LEFT OUTER JOIN ( SELECT DISTINCT 管理No, 発注日, 発注数 FROM T_発注 ) AS m ON m.管理No = a.管理No WHERE a.管理No = CAST(? as INT)
-- SQL_GET_CUSTOMER
SELECT * FROM ( SELECT CASE WHEN x.管理No IS NOT NULL THEN x.管理No ELSE y.管理No END AS 管理No ,CASE WHEN x.分納No IS NOT NULL THEN X.分納No ELSE y.分納No END AS 分納No ,x.回答日種別 ,x.回答日 ,x.回答日色区分 ,x.予定納入数 ,y.納入日 ,y.納入数 ,x.納入依頼日 ,y.出荷区分 ,y.検査出荷依頼日 ,y.検査完了日 ,y.検査出荷依頼数 FROM ( SELECT CASE WHEN a.管理No IS NOT NULL THEN a.管理No ELSE b.管理No END AS 管理No ,CASE WHEN a.分納No IS NOT NULL THEN a.分納No ELSE b.分納No END AS 分納No ,CASE COALESCE(a.回答日区分,'') WHEN '1' THEN '営回' WHEN '2' THEN '営発' WHEN '3' THEN '客回' WHEN '4' THEN '客発' ELSE '' END AS 回答日種別 ,a.回答日 ,CASE COALESCE(a.回答日区分,'') WHEN '1' THEN '0' /* 営回(black) */ WHEN '2' THEN '0' /* 営発(black) */ WHEN '3' THEN '2' /* 客回(blue) */ WHEN '4' THEN '1' /* 客発(red) */ ELSE '0' END AS 回答日色区分 ,a.予定納入数 ,b.依頼日 AS 納入依頼日 FROM T_納期回答 AS a FULL OUTER JOIN T_納入依頼 AS b ON b.管理No = a.管理No AND b.分納No = a.分納No ) AS x FULL OUTER JOIN ( SELECT CASE WHEN c.管理No IS NOT NULL THEN c.管理No ELSE d.管理No END AS 管理No ,CASE WHEN c.分納No IS NOT NULL THEN c.分納No ELSE d.分納No END AS 分納No ,CASE COALESCE(c.出荷区分,'') WHEN '1' THEN '振替出荷' WHEN '2' THEN '在庫出荷' WHEN '3' THEN '通常出荷' ELSE '' END AS 出荷区分 ,c.依頼日 AS 検査出荷依頼日 ,c.依頼数 AS 検査出荷依頼数 ,c.結果登録日 AS 検査完了日 ,d.納入日 ,d.依頼数 AS 納入数 FROM T_検査出荷依頼 AS c FULL OUTER JOIN T_売上 AS d ON d.管理No = c.管理No AND d.分納No = c.分納No ) AS y ON y.管理No = x.管理No AND y.分納No = x.分納No ) AS z WHERE z.管理No = CAST(? as INT) ORDER BY z.分納No
-- SQL_GET_SUPPLIER
SELECT a.管理No ,COALESCE(b.分納No,1) AS 分納No ,a.工程順序No ,a.作業区コード ,COALESCE(c.作業区略称,'') AS 作業区名 ,a.工程コード ,COALESCE(d.工程略称,'') AS 工程名 ,a.納期 ,b.督促日 ,b.希望納入日 ,b.希望納入数 ,b.回答日 ,b.受入日 ,b.受入数 ,b.受入形態 FROM T_生産計画詳細 AS a LEFT OUTER JOIN ( SELECT CASE WHEN x.管理No IS NOT NULL THEN x.管理No ELSE y.管理No END AS 管理No ,CASE WHEN x.工程順序No IS NOT NULL THEN x.工程順序No ELSE y.工程順序No END AS 工程順序No ,CASE WHEN x.分納No IS NOT NULL THEN x.分納No ELSE y.分納No END AS 分納No ,x.督促日 ,x.希望納入日 ,x.希望納入数 ,x.回答日 ,y.受入日 ,y.受入数 ,CASE COALESCE(y.受入形態区分,'') WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' ELSE '' END AS 受入形態 FROM T_納期回答依頼 AS x FULL OUTER JOIN T_工程受入 AS y ON y.管理No = x.管理No AND y.工程順序No = x.工程順序No AND y.分納No = x.分納No ) AS b ON b.管理No = a.管理No AND b.工程順序No = a.工程順序No LEFT OUTER JOIN M_作業区仕入先 AS c ON c.作業区コード = a.作業区コード LEFT OUTER JOIN M_工程 AS d ON d.工程コード = a.工程コード WHERE a.管理No = CAST(? as INT) ORDER BY a.管理No, a.工程順序No, 分納No
-- SQL_GET_REPLY
SELECT a.管理No ,a.分納No ,a.回答日区分 ,a.回答日 ,a.予定納入数 ,a.FAX作成 ,a.FAX備考 ,a.発行日 ,c.得意先コード ,a.得意先担当者名 ,a.担当者コード ,COALESCE(b.社員名,'') AS 担当者名 FROM T_納期回答 AS a INNER JOIN T_受注 AS c ON c.管理No = a.管理No LEFT OUTER JOIN M_社員 AS b ON b.社員コード = a.担当者コード WHERE a.管理No = CAST(? as INT) ORDER BY a.分納No
-- SQL_GET_REPLY_MAIL
SELECT a.管理No ,b.得意先コード ,COALESCE(d.得意先名,'') AS 得意先名 ,b.受注番号 ,b.枝番 ,b.品番 ,b.設変番号 ,b.品名 ,a.回答日 ,c.分納No ,c.回答日 AS 分納回答日 ,c.予定納入数 FROM ( SELECT 管理No ,MIN(回答日) AS 回答日 FROM T_納期回答 WHERE 回答日 IS NOT NULL GROUP BY 管理No ) AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No INNER JOIN T_納期回答 AS c ON c.管理No = a.管理No AND c.回答日 IS NOT NULL LEFT OUTER JOIN M_得意先 AS d ON d.得意先コード = b.得意先コード WHERE a.管理No = CAST(? as INT)
-- SQL_GET_PARAM
SELECT Key3, 値 FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ?
-- SQL_GET_REPORT
SELECT a.管理No ,a.受注番号 ,a.枝番 ,a.品番 ,a.設変番号 ,a.品名 ,a.得意先コード ,COALESCE(h.得意先名,'') AS 得意先名 ,COALESCE(b.得意先担当者名,'') AS 得意先担当者名 ,COALESCE(b.納入場所名,a.納入場所名) AS 納入場所名 ,COALESCE(b.出荷便区分,'1') AS 出荷便区分 ,c.回答日 ,COALESCE(b.出荷日,'') AS 出荷日 ,COALESCE(b.検査日,'') AS 検査日 ,c.予定納入数 ,COALESCE(b.納入形態区分,'1') AS 納入形態区分 ,CASE WHEN b.最終加工先コード IS NOT NULL THEN COALESCE(i.作業区名,'') ELSE COALESCE(f.作業区名,'') END AS 最終加工先名 ,COALESCE(b.入荷日, COALESCE(g.回答日,d.納期)) AS 入荷日 ,COALESCE(b.入荷時刻,'') AS 入荷時刻 ,COALESCE(b.備考,'') AS 備考 ,COALESCE(b.依頼日,CURRENT_DATE) AS 依頼日 ,COALESCE(b.発行者名,'') AS 発行者名 ,COALESCE(b.バージョン番号,0) AS バージョン番号 ,COALESCE(b.最終加工先コード,COALESCE(d.作業区コード,'')) AS 最終加工先コード FROM T_受注 AS a LEFT OUTER JOIN T_納入依頼 AS b ON b.管理No = a.管理No AND b.分納No = CAST(? as INT) LEFT OUTER JOIN M_作業区仕入先 as i ON i.作業区コード = b.最終加工先コード LEFT OUTER JOIN T_納期回答 AS c ON c.管理No = a.管理No AND c.分納No = CAST(? as INT) LEFT OUTER JOIN T_発注 AS d ON d.管理No = a.管理No AND d.最終工程区分 = true LEFT OUTER JOIN M_作業区仕入先 AS f ON f.作業区コード = d.作業区コード LEFT OUTER JOIN T_納期回答依頼 AS g ON g.管理No = d.管理No AND g.工程順序No = d.工程順序No AND g.分納No = CAST(? as INT) LEFT OUTER JOIN M_得意先 AS h ON h.得意先コード = a.得意先コード WHERE a.管理No = CAST(? as INT)
-- SQL_GET_REQUEST1
SELECT a.管理No ,COALESCE(b.分納数,1) AS 分納数 ,a.工程順序No ,a.作業区コード ,COALESCE(c.作業区略称,'') AS 作業区名 ,COALESCE(c.督促連絡方法,'2') AS 督促連絡方法 ,d.発注数 ,d.納期 FROM T_生産計画詳細 AS a LEFT OUTER JOIN ( SELECT 管理No ,MAX(分納No) AS 分納数 FROM T_納期回答依頼 GROUP BY 管理No ) AS b ON b.管理No = a.管理No LEFT OUTER JOIN M_作業区仕入先 AS c ON c.作業区コード = a.作業区コード LEFT OUTER JOIN T_発注 AS d ON d.管理No = a.管理No AND d.工程順序No = a.工程順序No WHERE a.管理No = CAST(? as INT) ORDER BY a.工程順序No
-- SQL_GET_REQUEST2
SELECT a.管理No ,a.分納No ,a.工程順序No ,a.希望納入日 ,a.希望納入数 ,a.回答依頼作成 ,a.督促日 ,a.回答期限 ,a.回答日 ,a.依頼書種別 ,a.連絡手段 ,a.作業区コード ,a.作業区担当者コード ,COALESCE(b.担当者名,'') AS 作業区担当者名 ,COALESCE(b.メールアドレス,'') AS メールアドレス ,a.作業区担当者名 ,a.担当者コード AS 連絡者コード ,COALESCE(c.社員名,'') AS 連絡者名 ,a.コメント FROM T_納期回答依頼 AS a LEFT OUTER JOIN M_作業区担当者 AS b ON b.作業区コード = a.作業区コード AND b.担当者コード = a.作業区担当者コード LEFT OUTER JOIN M_社員 AS c ON c.社員コード = a.担当者コード WHERE a.管理No = CAST(? as INT) ORDER BY a.分納No, a.工程順序No
-- SQL_GET_PARTS_BY_ORDER
SELECT DISTINCT 品番 FROM T_受注 WHERE 受注番号 &@ ? AND LENGTH(受注番号) = LENGTH(?)

