-- SQL_GET_ALL_COUNT
SELECT CAST(COUNT(x.管理No) AS INT)
-- SQL_GET_ALL_SELECT
SELECT x.管理No ,x.作業区コード ,COALESCE(y.作業区略称,'') AS 作業区名 ,x.作業区担当者名 ,z.受注番号 ,z.枝番 ,z.品番 ,z.設変番号 ,CASE WHEN x.依頼書種別 = '1' THEN COALESCE(t.工程略称,'') ELSE COALESCE(t.工程略称,'') || ' 他' END AS 工程名 ,x.希望納入日 ,x.連絡手段 ,CASE WHEN x.連絡手段 = '1' THEN 'メール' ELSE 'Fax' END AS 連絡手段名 ,x.依頼書種別 ,CASE WHEN x.依頼書種別 = '1' THEN '' ELSE '多工程' END AS 依頼書種別名
-- SQL_GET_ALL_FROM
FROM ( /* 通常 */ SELECT b.管理No ,b.工程順序No ,b.作業区コード ,b.作業区担当者名 ,b.希望納入日 ,b.連絡手段 ,b.依頼書種別 ,b.担当者コード FROM ( SELECT 管理No ,工程順序No ,MIN(分納No) AS 先頭分納No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '1' GROUP BY 管理No, 工程順序No ) AS a INNER JOIN T_納期回答依頼 AS b ON b.管理No = a.管理No AND b.工程順序No = a.工程順序No AND b.分納No = a.先頭分納No UNION ALL /* 多工程 */ SELECT c.管理No ,c.工程順序No ,c.作業区コード ,c.作業区担当者名 ,c.希望納入日 ,c.連絡手段 ,c.依頼書種別 ,c.担当者コード FROM ( SELECT 管理No ,MIN(工程順序No) AS 先頭工程順序No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' GROUP BY 管理No ) AS a INNER JOIN ( SELECT 管理No ,工程順序No ,MIN(分納No) AS 先頭分納No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' GROUP BY 管理No, 工程順序No ) AS b ON b.管理No = a.管理No AND b.工程順序No = a.先頭工程順序No INNEr JOIN T_納期回答依頼 AS c ON c.管理No = b.管理No AND c.工程順序No = b.工程順序No AND c.分納No = b.先頭分納No ) AS x LEFT OUTER JOIN M_作業区仕入先 AS y ON y.作業区コード = x.作業区コード INNER JOIN T_受注 AS z ON z.管理No = x.管理No INNER JOIN T_生産計画詳細 AS s ON s.管理No = x.管理No AND s.工程順序No = x.工程順序No LEFT OUTER JOIN M_工程 AS t ON t.工程コード = s.工程コード WHERE x.担当者コード = ?
-- SQL_GET_ALL_ORDER
ORDER BY COALESCE(y.表示順,0), x.作業区コード, x.作業区担当者名, x.希望納入日, z.品番
-- SQL_MULTIPLE
SELECT CAST(値 as INT) FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ? AND Key3 = ?
-- SQL_GET_REQUEST
SELECT A.管理No ,A.作業区コード ,COALESCE(B.作業区名,'') AS 作業区名 ,A.作業区担当者名 ,A.担当者コード ,COALESCE(C.社員名,'') AS 担当者名 ,CURRENT_DATE + interval '2 day' AS 回答期限日 ,'15' AS 回答期限時刻 ,CASE WHEN COALESCE(F.コメント,'') = '' THEN 'よろしくお願い申し上げます。' ELSE F.コメント END AS コメント FROM ( /* 通常 */ SELECT 管理No ,作業区コード ,作業区担当者名 ,担当者コード FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '1' UNION ALL /* 多工程 */ SELECT c.管理No ,c.作業区コード ,c.作業区担当者名 ,c.担当者コード FROM ( SELECT 管理No ,MIN(工程順序No) AS 先頭工程順序No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' GROUP BY 管理No ) AS a INNER JOIN ( SELECT 管理No ,工程順序No ,MIN(分納No) AS 先頭分納No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' GROUP BY 管理No, 工程順序No ) AS b ON b.管理No = a.管理No AND b.工程順序No = a.先頭工程順序No INNER JOIN T_納期回答依頼 AS c ON c.管理No = b.管理No AND c.工程順序No = b.工程順序No AND c.分納No = b.先頭分納No ) AS A LEFT OUTER JOIN M_作業区仕入先 AS B ON B.作業区コード = A.作業区コード LEFT OUTER JOIN M_社員 AS C ON C.社員コード = A.担当者コード INNER JOIN T_受注 AS D ON D.管理No = A.管理No LEFT OUTER JOIN ( SELECT 管理No ,MAX(督促日) AS 督促日 FROM T_納期回答依頼 WHERE 督促日 IS NOT NULL GROUP BY 管理No ) AS E ON E.管理No = A.管理No LEFT OUTER JOIN ( SELECT DISTINCT 管理No ,督促日 ,コメント FROM T_納期回答依頼 ) AS F ON F.管理No = E.管理No AND F.督促日 = E.督促日 WHERE A.管理No = CAST(? AS INT)
-- SQL_GET_MAIL
SELECT A.管理No ,A.作業区コード ,COALESCE(B.作業区名,'') AS 作業区名 ,A.作業区担当者コード ,A.作業区担当者名 ,C.メールアドレス AS 作業区担当者メールアドレス ,A.担当者コード ,COALESCE(D.社員名,'') AS 担当者名 ,COALESCE(D.メールアドレス,'') AS 担当者メールアドレス ,E.受注番号 ,E.品番 ,E.設変番号 ,E.枝番 FROM ( SELECT DISTINCT 管理No ,作業区コード ,作業区担当者コード ,作業区担当者名 ,担当者コード FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '1' AND 連絡手段 = '1' ) AS A LEFT OUTER JOIN M_作業区仕入先 AS B ON B.作業区コード = A.作業区コード LEFT OUTER JOIN M_作業区担当者 AS C ON C.作業区コード = A.作業区コード AND C.担当者コード = A.作業区担当者コード LEFT OUTER JOIN M_社員 AS D ON D.社員コード = A.担当者コード INNER JOIN T_受注 AS E ON E.管理No = A.管理No WHERE A.管理No
-- SQL_GET_MAIL_ORDER
ORDER BY E.品番, E.設変番号
-- SQL_GET_PARAM
SELECT Key3, 値 FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ?
-- SQL_GET_FAX
SELECT A.管理No ,A.作業区コード ,COALESCE(B.作業区名,'') AS 作業区名 ,A.作業区担当者名 ,A.担当者コード ,COALESCE(C.社員名,'') AS 担当者名 ,D.受注番号 ,D.品名 ,D.品番 ,D.設変番号 ,CASE WHEN E.依頼書種別 = '1' THEN '' ELSE CAST(E.工程順序No as VARCHAR) END AS 工程順序No ,CASE WHEN E.依頼書種別 = '1' THEN '' ELSE F.作業区コード END AS 作業区コード ,CASE WHEN E.依頼書種別 = '1' THEN '' ELSE COALESCE(G.作業区略称,'') END AS 作業区名 ,F.工程コード ,COALESCE(H.工程略称,'') AS 工程名 ,F.納期 ,E.希望納入日 ,COALESCE(J.受入日, I.回答日) AS 前工程納期 ,E.希望納入数 ,E.依頼書種別 ,CASE WHEN E.依頼書種別 = '1' THEN CAST(E.希望納入日 as VARCHAR) ELSE CAST(A.先頭希望納入日 as VARCHAR) END AS SORT1 ,CASE WHEN E.依頼書種別 = '1' THEN D.品番 ELSE D.受注番号 END AS SORT2 ,CASE WHEN E.依頼書種別 = '1' THEN '' ELSE CAST(E.分納No as VARCHAR) END AS SORT3 ,CASE WHEN E.依頼書種別 = '1' THEN '' ELSE CAST(E.工程順序No as VARCHAR) END AS SORT4 ,D.枝番 FROM ( /* 通常 */ SELECT DISTINCT 管理No ,作業区コード ,作業区担当者名 ,担当者コード ,CAST(NULL AS DATE) AS 先頭希望納入日 FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '1' AND 連絡手段 = '2' UNION ALL /* 多工程 */ SELECT c.管理No ,c.作業区コード ,c.作業区担当者名 ,c.担当者コード ,c.希望納入日 AS 先頭希望納入日 FROM ( SELECT 管理No ,MIN(工程順序No) AS 先頭工程順序No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' AND 連絡手段 = '2' GROUP BY 管理No ) AS a INNER JOIN ( SELECT 管理No ,工程順序No ,MIN(分納No) AS 先頭分納No FROM T_納期回答依頼 WHERE 回答依頼作成 = true AND 依頼書種別 = '2' GROUP BY 管理No, 工程順序No ) AS b ON b.管理No = a.管理No AND b.工程順序No = a.先頭工程順序No INNER JOIN T_納期回答依頼 AS c ON c.管理No = b.管理No AND c.工程順序No = b.工程順序No AND c.分納No = b.先頭分納No ) AS A LEFT OUTER JOIN M_作業区仕入先 AS B ON B.作業区コード = A.作業区コード LEFT OUTER JOIN M_社員 AS C ON C.社員コード = A.担当者コード INNER JOIN T_受注 AS D ON D.管理No = A.管理No INNER JOIN T_納期回答依頼 AS E ON E.管理No = A.管理No AND E.回答依頼作成 = true INNER JOIN T_生産計画詳細 AS F ON F.管理No = E.管理No AND F.工程順序No = E.工程順序No LEFT OUTER JOIN M_作業区仕入先 AS G ON G.作業区コード = F.作業区コード LEFT OUTER JOIN M_工程 AS H ON H.工程コード = F.工程コード LEFT OUTER JOIN T_納期回答依頼 AS I ON I.管理No = E.管理No AND I.工程順序No = (E.工程順序No - 1) AND I.分納No = E.分納No LEFT OUTER JOIN T_工程受入 AS J ON J.管理No = E.管理No AND J.工程順序No = (E.工程順序No - 1) AND J.分納No = E.分納No WHERE A.管理No
-- SQL_GET_FAX_ORDER
ORDER BY SORT1, SORT2, SORT3, SORT4

