-- SQL_MULTIPLE
SELECT CAST(値 as INT) FROM M_パラメータ WHERE Key1 = CAST(? AS INT) AND Key2 = ? AND Key3 = ?
-- SQL_GETALL_SELECT_1
SELECT a.品番 ,a.設変番号 ,a.在庫数 ,a.仮受在庫数 ,a.出荷依頼数 ,a.在庫数 - a.出荷依頼数 AS 有効在庫数 ,COALESCE(b.単価,0) AS 単価 ,CAST(trunc(COALESCE(b.単価,0) * a.在庫数 ,0) as BIGINT) AS 金額 ,CASE WHEN a.棚番2 = '' THEN a.棚番1 ELSE a.棚番1 || '-' || a.棚番2 END AS 棚番 ,a.備考 ,COALESCE(c.実績入数,0) AS 実績入数 ,a.補正入数 ,CASE WHEN a.補正入数 <> 0 THEN CEIL(a.在庫数 / a.補正入数) WHEN COALESCE(c.実績入数,0) <> 0 THEN CEIL(a.在庫数 / c.実績入数) ELSE 0 END AS 箱数 ,a.梱包区分 FROM M_在庫 AS a LEFT OUTER JOIN ( SELECT 品番, 設変番号, MIN(単価) AS 単価 FROM T_受注 WHERE 単価 <> 0 GROUP BY 品番, 設変番号 ) AS b ON b.品番 = a.品番 AND b.設変番号 = a.設変番号 LEFT OUTER JOIN ( SELECT x.品番, x.設変番号, MAX(COALESCE(y.個数,0)) AS 実績入数 FROM T_受注 AS x LEFT OUTER JOIN T_売上詳細 AS y ON y.管理No = x.管理No GROUP BY x.品番, x.設変番号 ) AS c ON c.品番 = a.品番 AND c.設変番号 = a.設変番号 %s %s %s ORDER BY a.品番, a.設変番号
-- SQL_GETALL_SELECT_COUNT_1
SELECT CAST(COUNT(a.品番) AS INT) FROM M_在庫 AS a LEFT OUTER JOIN ( SELECT 品番, 設変番号, MIN(単価) AS 単価 FROM T_受注 WHERE 単価 <> 0 GROUP BY 品番, 設変番号 ) AS b ON b.品番 = a.品番 AND b.設変番号 = a.設変番号 LEFT OUTER JOIN ( SELECT x.品番, x.設変番号, MAX(COALESCE(y.個数,0)) AS 実績入数 FROM T_受注 AS x LEFT OUTER JOIN T_売上詳細 AS y ON y.管理No = x.管理No GROUP BY x.品番, x.設変番号 ) AS c ON c.品番 = a.品番 AND c.設変番号 = a.設変番号 %s %s %s
-- SQL_GETALL_SELECT_2
SELECT a.品番 ,a.設変番号 ,a.在庫数 ,a.仮受在庫数 ,a.出荷依頼数 ,a.在庫数 - a.出荷依頼数 AS 有効在庫数 ,COALESCE(b.単価,0) AS 単価 ,CAST(trunc(COALESCE(b.単価,0) * a.在庫数 ,0) as BIGINT) AS 金額 ,CASE WHEN a.棚番2 = '' THEN a.棚番1 ELSE a.棚番1 || '-' || a.棚番2 END AS 棚番 ,a.備考 ,COALESCE(c.実績入数,0) AS 実績入数 ,a.補正入数 ,CASE WHEN a.補正入数 <> 0 THEN CEIL(a.在庫数 / a.補正入数) WHEN COALESCE(c.実績入数,0) <> 0 THEN CEIL(a.在庫数 / c.実績入数) ELSE 0 END AS 箱数 ,a.梱包区分 FROM M_在庫 AS a INNER JOIN ( SELECT y.品番, y.設変番号, y.単価 FROM ( SELECT DISTINCT 品番, 設変番号 FROM T_受注 %s ) AS x INNER JOIN ( SELECT 品番, 設変番号, MIN(単価) AS 単価 FROM T_受注 WHERE 単価 <> 0 GROUP BY 品番, 設変番号) AS y ON y.品番 = x.品番 AND y.設変番号 = x.設変番号 ) AS b ON b.品番 = a.品番 AND b.設変番号 = a.設変番号 LEFT OUTER JOIN ( SELECT x.品番, x.設変番号, MAX(COALESCE(y.個数,0)) AS 実績入数 FROM T_受注 AS x LEFT OUTER JOIN T_売上詳細 AS y ON y.管理No = x.管理No GROUP BY x.品番, x.設変番号 ) AS c ON c.品番 = a.品番 AND c.設変番号 = a.設変番号 %s ORDER BY a.品番, a.設変番号
-- SQL_GETALL_SELECT_COUNT_2
SELECT CAST(COUNT(a.品番) AS INT) FROM M_在庫 AS a INNER JOIN ( SELECT y.品番, y.設変番号, y.単価 FROM ( SELECT DISTINCT 品番, 設変番号 FROM T_受注 %s ) AS x INNER JOIN ( SELECT 品番, 設変番号, MIN(単価) AS 単価 FROM T_受注 WHERE 単価 <> 0 GROUP BY 品番, 設変番号) AS y ON y.品番 = x.品番 AND y.設変番号 = x.設変番号 ) AS b ON b.品番 = a.品番 AND b.設変番号 = a.設変番号 LEFT OUTER JOIN ( SELECT x.品番, x.設変番号, MAX(COALESCE(y.個数,0)) AS 実績入数 FROM T_受注 AS x LEFT OUTER JOIN T_売上詳細 AS y ON y.管理No = x.管理No GROUP BY x.品番, x.設変番号 ) AS c ON c.品番 = a.品番 AND c.設変番号 = a.設変番号 %s
-- SQL_GETHISTORYLIST_SELECT
SELECT * FROM ( SELECT b.品番 ,b.設変番号 ,COALESCE(c.品名,'') AS 品名 ,a.受入日 AS 入出庫日 ,'仕入' AS 受払区分 ,a.受入数 ,0 AS 払出数 ,b.受注番号 ,b.枝番 ,'' AS 備考 ,'' AS 棚番 ,4 AS 順位 ,CAST(NULL as TIMESTAMP) AS 更新日時 FROM T_工程受入 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.品番 = ? AND b.設変番号 = ? INNER JOIN T_発注 AS d ON d.管理No = a.管理No AND d.工程順序No = a.工程順序No AND d.最終工程区分 = true LEFT OUTER JOIN M_部品 AS c ON c.品番 = b.品番 UNION ALL SELECT b.品番 ,b.設変番号 ,COALESCE(c.品名,'') AS 品名 ,a.納入日 AS 入出庫日 ,'売上' AS 受払区分 ,0 AS 受入数 ,a.依頼数 AS 払出数 ,b.受注番号 ,b.枝番 ,'' AS 備考 ,'' AS 棚番 ,2 AS 順位 ,CAST(NULL as TIMESTAMP) AS 更新日時 FROM T_売上 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.品番 = ? AND b.設変番号 = ? LEFT OUTER JOIN M_部品 AS c ON c.品番 = b.品番 UNION ALL SELECT a.品番 ,a.設変番号 ,COALESCE(b.品名,'') AS 品名 ,a.登録日 AS 入出庫日 ,'調整' AS 受払区分 ,CASE WHEN a.調整数 > 0 THEN a.調整数 ELSE 0 END AS 受入数 ,CASE WHEN a.調整数 < 0 THEN ABS(a.調整数) ELSE 0 END AS 払出数 ,'' AS 受注番号 ,'' AS 枝番 ,a.備考 ,CASE WHEN a.棚番2 = '' THEN a.棚番1 ELSE a.棚番1 || '-' || a.棚番2 END AS 棚番 ,1 AS 順位 ,a.更新日時 FROM T_受払 AS a LEFT OUTER JOIN M_部品 AS b ON b.品番 = a.品番 WHERE a.品番 = ? AND a.設変番号 = ? UNION ALL SELECT b.品番 ,b.設変番号 ,COALESCE(c.品名,'') AS 品名 ,a.返品日 AS 入出庫日 ,'返品' AS 受払区分 ,0 AS 受入数 ,a.数量 AS 払出数 ,b.受注番号 ,b.枝番 ,'' AS 備考 ,'' AS 棚番 ,3 AS 順位 ,CAST(NULL as TIMESTAMP) AS 更新日時 FROM T_受入返品 AS a INNER JOIN T_受注 AS b ON b.管理No = a.管理No AND b.品番 = ? AND b.設変番号 = ? LEFT OUTER JOIN M_部品 AS c ON c.品番 = b.品番 ) AS x ORDER BY x.入出庫日 DESC, x.順位, x.更新日時 DESC

