-- SQL_GETALL_SELECT_COUNT
SELECT CAST(COUNT(SeqNo) AS INT) FROM T_棚卸
    -- SQL_GETALL_WHERE_TANAOROSHI
    WHERE 棚卸月 = ? AND 作業区コード = ?
    
    -- SQL_GETALL_WHERE_SEQNO
    WHERE SeqNo = CAST(? AS INT)


