-- SQL_REPORT_24_SELECT_TEMPLATE
SELECT a.supplier_code ,COALESCE(b.supplier_name,'') AS supplier_name ,a.process_code ,COALESCE(c.process_abbreviation,'') AS process_name ,d.incoming_order_no ,d.branch_no ,d.part_no ,d.engineering_change_no ,d.part_name ,a.placing_order_DATE ,a.deadline ,CASE WHEN f.response_DATE IS NOT NULL THEN CAST(DATE_PART('YEAR',f.response_DATE) as VARCHAR) || '/' || CAST(DATE_PART('MONTH',f.response_DATE) as VARCHAR) || '/' || CAST(DATE_PART('DAY',f.response_DATE) as VARCHAR) ELSE '' END AS response_DATE ,COALESCE(f.requested_delivery_quantity,0) AS 回答数 ,a.placing_order_quantity ,CASE COALESCE(h.acceptance_form_type,'') WHEN '1' THEN '完納' WHEN '2' THEN '打切り' WHEN '3' THEN '分納' ELSE '' END AS 受入形態 ,COALESCE(g.acceptance_quantity,0) AS acceptance_quantity ,a.unit_price ,CAST(TRUNC(a.unit_price * a.placing_order_quantity,0) as BIGINT) AS 発注price ,d.unit_price AS 売value ,CASE COALESCE(k.price_round_type,'1') WHEN '1' THEN CAST(FLOOR(d.unit_price * d.incoming_order_quantity) as BIGINT) WHEN '2' THEN CAST(CEIL(d.unit_price * d.incoming_order_quantity) as BIGINT) ELSE CAST(ROUND((d.unit_price * d.incoming_order_quantity),0) as BIGINT) END AS 売valueprice ,COALESCE(i.supplier_code,'') AS next_process_code ,CASE WHEN i.supplier_code IS NULL THEN '古河（本社）' ELSE COALESCE(j.supplier_name,'') END AS next_process_name %s %s %s %s
-- SQL_REPORT_24_COMMON(%s1)
FROM t_placing_orders AS a LEFT OUTER JOIN m_suppliers AS b ON b.supplier_code = a.supplier_code LEFT OUTER JOIN m_processes AS c ON c.process_code = a.process_code INNER JOIN t_incoming_orders AS d ON d.management_no = a.management_no LEFT OUTER JOIN m_customers AS k ON k.customer_code = d.customer_code LEFT OUTER JOIN ( SELECT management_no ,process_sort_no ,MIN(partial_delivery_no) AS partial_delivery_no FROM t_deadline_response_requests WHERE response_DATE IS NOT NULL GROUP BY management_no, process_sort_no ) AS e ON e.management_no = a.management_no AND e.process_sort_no = a.process_sort_no LEFT OUTER JOIN t_deadline_response_requests AS f ON f.management_no = e.management_no AND f.process_sort_no = e.process_sort_no AND f.partial_delivery_no = e.partial_delivery_no LEFT OUTER JOIN ( SELECT placing_order_no ,MAX(partial_delivery_no) AS partial_delivery_no ,SUM(acceptance_quantity) AS acceptance_quantity FROM t_process_acceptances GROUP BY placing_order_no ) AS g ON g.placing_order_no = a.placing_order_no LEFT OUTER JOIN t_process_acceptances AS h ON h.placing_order_no = g.placing_order_no AND h.partial_delivery_no = g.partial_delivery_no LEFT OUTER JOIN t_production_plan_details AS i ON i.management_no = a.management_no AND i.process_sort_no = (a.process_sort_no + 1) LEFT OUTER JOIN m_suppliers AS j ON j.supplier_code = i.supplier_code WHERE a.placing_order_DATE BETWEEN CAST(CASE WHEN ? = '' THEN '2000-01-01' ELSE ? END as DATE) AND CAST(CASE WHEN ? = '' THEN '9999-12-31' ELSE ? END as DATE)
    -- SQL_REPORT_24_WHERE_SAGYOUKU(%s2)
    AND a.supplier_code = ?
    -- SQL_REPORT_24_WHERE_HINBANI(%s3)
    AND d.part_no &^ ?
    -- SQL_REPORT_24_ORDERBY(%s4)
    ORDER BY a.supplier_code, d.part_no, a.placing_order_DATE, a.deadline


