-- SQL_GET_ALL_COUNT
SELECT CAST(COUNT(a.管理No) AS INT)
-- SQL_GET_ALL_FROM_CLAUSE
FROM T_受注 AS a LEFT OUTER JOIN M_得意先 AS b ON b.得意先コード = a.得意先コード LEFT OUTER JOIN M_社員 AS c ON c.社員コード = a.担当者コード
-- SQL_GET_ALL_WHERE_CLAUSE
WHERE

    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_DATE
    a.受注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)
    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_NO
    AND a.受注番号 &@ ? AND LENGTH(a.受注番号) = LENGTH(?)

    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_DATE
    a.受注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)
    -- SQL_GET_ALL_WHERE_CLAUSE_PARTS_NO
    AND a.品番 &@ ? AND LENGTH(a.品番) = LENGTH(?)

    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_DATE
    a.受注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)
    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_NO
    AND a.受注番号 &@ ? AND LENGTH(a.受注番号) = LENGTH(?)

    -- SQL_GET_ALL_WHERE_CLAUSE_ORDER_DATE
    a.受注日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)

    -- SQL_GET_ALL_WHERE_CLAUSE_MANAGEMENT_NO
    a.管理No = CAST(? as INT)
