-- SQL_GETALL_COUNT
SELECT CAST(COUNT(SeqNo) AS INT) FROM T_売上返品 AS a LEFT OUTER JOIN M_得意先 AS b ON b.得意先コード = a.得意先コード
-- SQL_GETALL_WHERE_HENPINBI
WHERE a.返品日 BETWEEN CAST(? as DATE) AND CAST(? as DATE)


